# Python Numpy Part 2


## Import Numpy


In [4]:
import numpy as np

In [5]:
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

print("a Array")
print(a)
print(a.shape)
print(a.ndim)
print("\n")

print("b Array")
print(b)
print(b.shape)
print(b.ndim)
print("\n")

a Array
[[4 5 2]
 [5 3 8]]
(2, 3)
2


b Array
[[21 26 23]
 [27 23 24]]
(2, 3)
2




## Concatenate


In [6]:
con_row = np.concatenate((a, b), axis=0)  # row wise
print("Concatenate a,b row wise axis=0")
print(con_row)
print("\n")

con_col = np.concatenate((a, b), axis=1)  # column wise
print("Concatenate a,b column wise axis=1")
print(con_col)
print("\n")

Concatenate a,b row wise axis=0
[[ 4  5  2]
 [ 5  3  8]
 [21 26 23]
 [27 23 24]]


Concatenate a,b column wise axis=1
[[ 4  5  2 21 26 23]
 [ 5  3  8 27 23 24]]




In [7]:
# error

# row-wise concatenate korar shomoi column same thakbe
# col-wise concatenate korar shomoi row same thakte hobe

x = np.random.randint(1, 10, size=(2, 3))
y = np.random.randint(1, 10, size=(1, 3))

print(x)
print("\n")
print(y)
print("\n")

# r = np.concatenate((x,y),axis =0 )
r = np.concatenate((x, y), axis=1)
print(r)

[[1 9 3]
 [4 4 8]]


[[9 2 4]]




ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## Transpose


In [ ]:
mat = np.array([[10, 20, 30], [30, 40, 50]])
print("Normal mat array")
print(mat)
print("\n")

transpose = mat.T
print("Transpose Array")
print(transpose)
print("\n")

Normal mat array
[[10 20 30]
 [30 40 50]]


Transpose Array
[[10 30]
 [20 40]
 [30 50]]




## Array split


In [ ]:
tmp_arr = np.random.randint(1, 10, size=(10,))
print("Normal Array")
print(tmp_arr)
print("\n")

splitted_array = np.array_split(tmp_arr, 3)
print("Unequal division using Numpy array_split of tmp_arr")
print(splitted_array)
print("\n")

# split -> equal division
splittedarr = np.split(tmp_arr, 5)
print("Equal division using numpy split of tmp_arr")
print(splittedarr)
print("\n")

Normal Array
[6 1 5 3 8 7 8 4 8 9]


Unequal division using Numpy array_split of tmp_arr
[array([6, 1, 5, 3], dtype=int32), array([8, 7, 8], dtype=int32), array([4, 8, 9], dtype=int32)]


Equal division using numpy split of tmp_arr
[array([6, 1], dtype=int32), array([5, 3], dtype=int32), array([8, 7], dtype=int32), array([8, 4], dtype=int32), array([8, 9], dtype=int32)]




## Arithmetic Operator and Mathematical Functions


### Basic mathematical operation (+ - \* / %)


In [ ]:
# faster for vectorization

x = np.array([10, 8, 30, 100])
y = np.array([2, 3, 4, 5])

print("First Array")
print(x)
print("\n")

print("Second Array")
print(y)
print("\n")

add = np.add(x, y)
add_two = x + y
print("Addition of array: ", add)
print("Addition 2 of array: ", add_two)
print("\n")

sub = x - y
print("Subtraction of array: ", sub)
print("\n")

mul = x * y
print("Multiplication of array: ", mul)
print("\n")

div = x / y
print("Divition of array: ", div)
print("\n")

remainder = x % y
print("Remainder of array: ", remainder)
print("\n")

First Array
[ 10   8  30 100]


Second Array
[2 3 4 5]


Addition of array:  [ 12  11  34 105]
Addition 2 of array:  [ 12  11  34 105]


Subtraction of array:  [ 8  5 26 95]


Multiplication of array:  [ 20  24 120 500]


Divition of array:  [ 5.          2.66666667  7.5        20.        ]


Remainder of array:  [0 2 2 0]




In [ ]:
# different
s = np.sum(x)
print(s)

# prefix sum
cumul = np.cumulative_sum(x)
print(cumul)

148
[ 10  18  48 148]


### Trigonometry Operation (sin, cos, radiant, degree)


In [ ]:
sin_val = np.sin(x)
print("sin of array: ", sin_val)
print("\n")

cos_val = np.cos(x)
print("cos of array: ", cos_val)
print("\n")

deg_con = np.rad2deg(x)
print("Radiant to degree of array: ", deg_con)
print("\n")

deg_con = np.deg2rad(x)
print("Degree to radiant of array: ", deg_con)
print("\n")

sin of array:  [-0.54402111  0.98935825 -0.98803162 -0.50636564]


cos of array:  [-0.83907153 -0.14550003  0.15425145  0.86231887]


Radiant to degree of array:  [ 572.95779513  458.3662361  1718.87338539 5729.57795131]


Degree to radiant of array:  [0.17453293 0.13962634 0.52359878 1.74532925]




### Log


In [ ]:
base_10_log_val = np.log10(x)
print("10 based log of x:", base_10_log_val)


two_diye_bhag = np.log2(x)
print("02 based log of x:", two_diye_bhag)

sqrt = np.sqrt(x)
print("square root of x:", sqrt)

10 based log of x: [1.         0.90308999 1.47712125 2.        ]
02 based log of x: [3.32192809 3.         4.9068906  6.64385619]
square root of x: [ 3.16227766  2.82842712  5.47722558 10.        ]


## Logical Function


In [ ]:
x = np.array([10, 8, 16, 100])
y = np.array([2, 3, 16, 5])

greater_than = x > y
equal = x == y

print("x is greater then y =", greater_than)

print("x is equal to y =", equal)

print("x is greater then y to all =", np.all(greater_than))

print("x is greater then y to any =", np.any(equal))

x is greater then y = [ True  True False  True]
x is equal to y = [False False  True False]
x is greater then y to all = False
x is greater then y to any = True


## Sorting


In [ ]:
z = x.copy()

print("Copy of array x in z", z)

z.sort()

print("Sorting of array z", z)

Copy of array x in z [ 10   8  16 100]
Sorting of array z [  8  10  16 100]


In [ ]:
# copy sorting
print("Array x", x)

sort_arr = np.sort(x)

print("Copy of sort x", sort_arr)

print("Array x", x)

Array x [ 10   8  16 100]
Copy of sort x [  8  10  16 100]
Array x [ 10   8  16 100]


In [ ]:
# 2d array sorting
mat = np.array([[10, 3, 5], [8, 4, 9]])

# horizon axis = 1

hor_sort = np.sort(mat, axis=1)
print(hor_sort)

# vertical axis = 0

vert_sort = np.sort(mat, axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## Searching


In [ ]:
index = np.where(x == 8)  # returns index
print(index)

arr = np.where(x > 8, x, 0)  # returns array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [ ]:
tmp_arr = np.array([10, 100, 8, 16, 100])

maximum_value_indx = np.argmax(tmp_arr)
minimum_value_indx = np.argmin(tmp_arr)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


## counting in ndarray


In [ ]:
a = np.random.randint(1, 100, size=(5, 20))
print("a Array:")
print(a)
print("\n")

tmp_condition_arr = np.count_nonzero(a == 97)
print("How many element is equal to 97:", tmp_condition_arr)
print("\n")

unique_value, count = np.unique(a, return_counts=True)
print("All unique value of a array", unique_value)
print("\n")
print("How many this element have in this array", count)
print("\n")

a Array:
[[11 56 65 43  5 21 89 70 48 97 93 27  1 98 49 25 45 48 69  1]
 [ 6  5 69 31 72 70 39 76 54 75 91 99 38 18  3 91 41 83 54 24]
 [63 43 99 83 77 92 39 99 95 47 67 48 94 21 44 77 13 60 96 89]
 [31 85 90  3 19 39 79 10 59 76 83 30 42 36  8 15 71 71 18 33]
 [81 81 62 23 23 65 75 86 85  5 39 31 23 84 67 47 58 11 24 60]]


How many element is equal to 97: 1


All unique value of a array [ 1  3  5  6  8 10 11 13 15 18 19 21 23 24 25 27 30 31 33 36 38 39 41 42
 43 44 45 47 48 49 54 56 58 59 60 62 63 65 67 69 70 71 72 75 76 77 79 81
 83 84 85 86 89 90 91 92 93 94 95 96 97 98 99]


How many this element have in this array [2 2 3 1 1 1 2 1 1 2 1 2 3 2 1 1 1 3 1 1 1 4 1 1 2 1 1 2 3 1 2 1 1 1 2 1 1
 2 2 2 2 2 1 2 2 2 1 2 3 1 2 1 2 1 2 1 1 1 1 1 1 1 3]




## linear algebra


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

B = np.array([[7, 8], [9, 10], [11, 12]])

sq_mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# a er column and b er row same length hote hobe
dot_product = np.dot(A, B)
print("Dot product of A,B array: ")
print(dot_product)
print("\n")

# trace
print("Trace of B array: ", np.trace(B))
print("\n")

print("Determinant of a square matrix A array: ", np.linalg.det(sq_mat))

print("Rank of a matrix A array: ", np.linalg.matrix_rank(sq_mat))

Dot product of A,B array: 
[[ 58  64]
 [139 154]]


Trace of B array:  17


Determinant of a square matrix A array:  6.66133814775094e-16
Rank of a matrix A array:  2


## Statistical function


In [ ]:
# data load

data = np.genfromtxt("./../data/student_scores.csv", delimiter=",", skip_header=1)

print(data)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [ ]:
# statistics
math_marks = data[::, :1]

print("Math results:\n", math_marks.T)

max_math_marks = np.max(math_marks)
print("Max mark of math results: ", max_math_marks)

min_math_marks = np.min(math_marks)
print("Min mark of math results: ", min_math_marks)

average_math_marks = np.mean(math_marks)
print("Average mark of math results: ", average_math_marks)

median_math_marks = np.median(math_marks)
print("Median mark of math results: ", median_math_marks)

std_math_marks = np.std(math_marks)
print("Standart deviation mark of math results: ", std_math_marks)

Math results:  [[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
Max mark of math results:  95.0
Min mark of math results:  45.0
Average mark of math results:  73.15
Median mark of math results:  73.5
Standart deviation mark of math results:  13.788672887555204


In [ ]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]
