# Numpy


## Basic Array

### Ndarray
### Array attributes
### Ndarray data type

In [209]:
import numpy as np

arr1d = np.array(
    [1, 2, 3],
    dtype=np.int8,
)
arr2d = np.array(
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    dtype=np.int8,
)
arr3d = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [10, 11, 12],
            [13, 14, 15],
            [16, 17, 18],
        ],
        [
            [19, 20, 21],
            [22, 23, 24],
            [25, 26, 27],
        ],
    ],
    dtype=np.int8,
)
print("NumPy Array:")
print(arr1d)
print("\n")
print(arr2d)
print("\n")
print(arr3d)
print("\n")

print("1D Array Shape:", arr1d.shape)
print("2D Array Shape:", arr2d.shape)
print("3D Array Shape:", arr3d.shape)
print("\n")

print("1D Array Data Type:", arr1d.dtype)
print("2D Array Data Type:", arr2d.dtype)
print("3D Array Data Type:", arr3d.dtype)
print("\n")

print("1D Array Dimension:", arr1d.ndim)
print("2D Array Dimension:", arr2d.ndim)
print("3D Array Dimension:", arr3d.ndim)
print("\n")

print("1D Array Size:", arr1d.size)
print("2D Array Size:", arr2d.size)
print("3D Array Size:", arr3d.size)
print("\n")

print("1D Array Single Item Size in Bytes:", arr1d.itemsize)
print("2D Array Single Item Total Size in Bytes:", arr2d.itemsize)
print("3D Array Single Item Total Size in Bytes:", arr3d.itemsize)
print("\n")

print("1D Array Size in Bytes:", arr1d.nbytes)
print("2D Array Size in Bytes:", arr2d.nbytes)
print("3D Array Size in Bytes:", arr3d.nbytes)
print("\n")

NumPy Array:
[1 2 3]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


1D Array Shape: (3,)
2D Array Shape: (3, 3)
3D Array Shape: (3, 3, 3)


1D Array Data Type: int8
2D Array Data Type: int8
3D Array Data Type: int8


1D Array Dimension: 1
2D Array Dimension: 2
3D Array Dimension: 3


1D Array Size: 3
2D Array Size: 9
3D Array Size: 27


1D Array Single Item Size in Bytes: 1
2D Array Single Item Total Size in Bytes: 1
3D Array Single Item Total Size in Bytes: 1


1D Array Size in Bytes: 3
2D Array Size in Bytes: 9
3D Array Size in Bytes: 27




## Array creation from existing data

### List

In [210]:
# List 

lst = [10,20,30,40 , 40.5] 
lst_arr = np.array(lst, dtype=np.int8) 
print("List to Array")
print(lst_arr) 
print("Array Data Type:", lst_arr.dtype)
print("\n")

List to Array
[10 20 30 40 40]
Array Data Type: int8




### Matrix

In [211]:
# Matrix

matrix = [ 
            [1,2,3], # row1
            [4,5,6]  # row2
         ]
matrix_arr = np.array(matrix, dtype=np.int8) 
print("Matrix to Array")
print(matrix_arr) 
print("Array Data Type:", matrix_arr.dtype)
print("\n")

Matrix to Array
[[1 2 3]
 [4 5 6]]
Array Data Type: int8




### Tuple

In [212]:
# Tuple 

tpl = (1,2,3) 
tpl_arr = np.array(tpl, dtype=np.int8)
print("Tuple to Array")
print(tpl_arr) 
print("Array Data Type:", tpl_arr.dtype)
print("\n")


Tuple to Array
[1 2 3]
Array Data Type: int8




### Set

In [213]:
# Set 

st = { 1, 2, 3 }
st_arr = np.array(st)
print("Set to Array")
print(st_arr)
print("Array Data Type:", st_arr.dtype)
print("\n")

st_arr = np.array(list(st), dtype=np.int8)
print(st_arr)
print("Array Data Type:", st_arr.dtype)
print("\n")

Set to Array
{1, 2, 3}
Array Data Type: object


[1 2 3]
Array Data Type: int8




### Dictionary

In [214]:
# Dictionary 

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }
keys = dc.keys()
values = dc.values()
items = dc.items()

print("Dictionary Keys to Array")
keys_arr = np.array(keys)
print(keys_arr) 
print("Array Data Type:", keys_arr.dtype)
print("\n")

print("Dictionary Values to Array")
values_arr = np.array(values)
print(values_arr) 
print("Array Data Type:", values_arr.dtype)
print("\n")

print("Dictionary Items to Array")
items_arr = np.array(items)
print(items_arr) 
print("Array Data Type:", items_arr.dtype)
print("\n")

Dictionary Keys to Array
dict_keys(['a', 'b', 'c'])
Array Data Type: object


Dictionary Values to Array
dict_values([10, 20, 30])
Array Data Type: object


Dictionary Items to Array
dict_items([('a', 10), ('b', 20), ('c', 30)])
Array Data Type: object




## Creating Arrays from scratch

### zeros, zero_like

In [215]:
# np.zeros

zero_arr = np.zeros((3,3),dtype=np.int8)
print("Zero Array")
print(zero_arr)
print("Array Data Type:", zero_arr.dtype)
print("\n")

zero_arr3d = np.zeros_like(arr3d) ## arr3d shape same 
print("Zero Like Array of arr3d")
print(zero_arr3d)
print("Array Data Type:", zero_arr3d.dtype) 

Zero Array
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Array Data Type: int8


Zero Like Array of arr3d
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
Array Data Type: int8


### ones, one_like

In [216]:
#np.ones

one_arr = np.ones((3,3),dtype=np.int8)
print("One Array")
print(one_arr) 
print("Array Data Type:", one_arr.dtype) 
print("\n")

one_arr3d = np.ones_like(arr3d) ## arr3d shape same  
print("One Like Array of arr3d")
print(one_arr3d)
print("Array Data Type:", one_arr3d.dtype) 
print("\n")

One Array
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Array Data Type: int8


One Like Array of arr3d
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
Array Data Type: int8




### empty, empty_like

In [217]:
#np.empty
empty_arr = np.empty((3,3), dtype=np.int8)
print("Empty Array")
print(empty_arr) 
print("Array Data Type:", empty_arr.dtype) 
print("\n")

empty_arr3d = np.empty_like(arr3d, dtype=np.int8) ## arr3d shape same 
print("Empty Like Array of arr3d")
print(empty_arr3d)
print("Array Data Type:", empty_arr3d.dtype) 
print("\n")

Empty Array
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Array Data Type: int8


Empty Like Array of arr3d
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
Array Data Type: int8




### full, full_like

In [218]:
#np.full 

full_arr = np.full((4,3),np.inf)
print("Full Array")
print(full_arr) 
print("Array Data Type:", full_arr.dtype) 
print("\n")

full_arr3d = np.full_like(arr3d, 100, dtype=np.int8) 
print("Full Like Array of arr3d")
print(full_arr3d)
print("Array Data Type:", full_arr3d.dtype)
print("\n")

Full Array
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
Array Data Type: float64


Full Like Array of arr3d
[[[100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]
  [100 100 100]]]
Array Data Type: int8




### random values

In [219]:
# np.random.rand(shape) 

rand_arr = np.random.rand(3,3) # 0 ->1 
print("Random Rand Array")
print(rand_arr) 
print("Array Data Type:", rand_arr.dtype) 
print("\n")

# np.random.randint(start,end, shape) 

randint_arr = np.random.randint(1,10 , (3,3))  
print("Random Randint Array")
print(randint_arr) 
print("Array Data Type:", randint_arr.dtype) 
print("\n")

# np.random.uniform(start,end, shape) 

uniform_arr = np.random.uniform(0, 10, 5)   
print("Random Uniform Array")
print(uniform_arr) 
print("Array Data Type:", uniform_arr.dtype) 
print("\n")

Random Rand Array
[[0.65967327 0.42492809 0.97374821]
 [0.35094325 0.85915031 0.34931852]
 [0.02426697 0.14436662 0.06665351]]
Array Data Type: float64


Random Randint Array
[[1 6 5]
 [8 7 4]
 [8 1 9]]
Array Data Type: int32


Random Uniform Array
[1.74611459 1.40689552 5.96073981 7.18146659 2.44423736]
Array Data Type: float64




### Range functions

In [220]:
# np.arange(first , end , step ) -> similar to range function 

ararr = np.arange(1 , 10 ,1 )
print("Numpy Arange function")
print(ararr) 
print("Array Data Type:", ararr.dtype)
print("\n")

# np.linspace(start , end(included) , quantity) 

arr = np.linspace(0, 4 ,6)
print("Numpy Linspace function")
print(arr) 
print("Array Data Type:", arr.dtype)
print("\n")

# np.logspace(start , end(included) , quantity ) 

arr = np.logspace(0 , 4 ,6, base =2) 
print("Numpy Logspace function")
print(arr)
print("Array Data Type:", arr.dtype)
print("\n")

Numpy Arange function
[1 2 3 4 5 6 7 8 9]
Array Data Type: int64


Numpy Linspace function
[0.  0.8 1.6 2.4 3.2 4. ]
Array Data Type: float64


Numpy Logspace function
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
Array Data Type: float64




## Linear algebra

### Basic matrix

In [221]:
diagonal_matrix = np.diag([1, 2, 3])

print("Diagonal Matrix")
print(diagonal_matrix)
print("Array Data Type:", diagonal_matrix.dtype)
print("Array Shape:", diagonal_matrix.shape)
print("Array Dimension:", diagonal_matrix.ndim)
print("\n")

Diagonal Matrix
[[1 0 0]
 [0 2 0]
 [0 0 3]]
Array Data Type: int64
Array Shape: (3, 3)
Array Dimension: 2




### Identity Matrix

In [222]:
# identity matrix 

identity_mat = np.eye(3)
print("Identity Matrix 1")
print(identity_mat)
print("Array Data Type:", identity_mat.dtype)
print("Array Shape:", identity_mat.shape)
print("Array Dimension:", identity_mat.ndim)
print("\n")

# np.eye(row , column,k) 

mat2 = np.eye(3,3)
print("Identity Matrix Row Column")
print(mat2)
print("Array Data Type:", mat2.dtype)
print("Array Shape:", mat2.shape)
print("Array Dimension:", mat2.ndim)
print("\n")

mat3 = np.eye(3,3,1)
print("Identity Matrix Row Column Key")
print(mat3)
print("Array Data Type:", mat3.dtype)
print("Array Shape:", mat3.shape)
print("Array Dimension:", mat3.ndim)
print("\n")

Identity Matrix 1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array Data Type: float64
Array Shape: (3, 3)
Array Dimension: 2


Identity Matrix Row Column
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array Data Type: float64
Array Shape: (3, 3)
Array Dimension: 2


Identity Matrix Row Column Key
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Array Data Type: float64
Array Shape: (3, 3)
Array Dimension: 2




## Indexing and Slicing

In [223]:
#indexing 

arr_1d = np.array(
    [1, 2, 3],
)
arr_2d = np.array(
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
)

print("Print Array")
print(arr_1d)
print(arr_2d)
print("\n")

Print Array
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]




### Indexing

In [224]:
# print(arr1s)
arr_2d[0][2]= 100
print("Change Value of Index [0][2] of 2D Array")
print(arr_2d)
print("\n")

Change Value of Index [0][2] of 2D Array
[[  1   2 100]
 [  4   5   6]
 [  7   8   9]]




### Slicing 

In [225]:
#slicing 
#1d = arr[start:end:step] 

arr_1d_mod = arr_1d[1:3].copy() 
print("Slicing and Copy of 1D Array")
print(arr_1d_mod)
print("\n")

arr_1d_mod[1] = 200
print("Change Value of Index [1] of 1D Array")
print(arr_1d_mod) 
print("\n")

Slicing and Copy of 1D Array
[2 3]


Change Value of Index [1] of 1D Array
[  2 200]




### 2d slicing 

In [226]:
# arr[ row_start : row_end : step , column_start : column_end : step ]

#getting a row 

row_0 = arr_2d[0:1 ,]
row_1= arr_2d[1: , ]
print(row_0)
print(row_1)


#getting a column 

col_0 = arr_2d[:: ,0:1]
col_1 = arr_2d[::,1:2]
print(col_0)
print(col_1)

#getting a portion 

portion = arr_2d[:: , 0:2] 
print(portion)

[[  1   2 100]]
[[4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[1 2]
 [4 5]
 [7 8]]


### Advanced Indexing

In [227]:
lst = np.array([ 10 , 20 ,30 ,40 ]) 

values = lst[[0,3,1]]
print("Print Index [[0,3,1]] of 1D Array")
print(values)

Print Index [[0,3,1]] of 1D Array
[10 40 20]


In [229]:
print("Print 2D Array")
print(arr_2d)
print("\n")

print("Print Index [[0,1] , [1,2]] of 2D Array")
print(arr_2d[[0,1] , [1,2]])
print("\n")

print("Print arr_2d[arr_1d>1] of 2D Array")
print(arr_2d[arr_1d>1])
print("\n")

arr_2d[arr_2d>2] = 1
print("Change Value of Index [arr_2d>2] of 2D Array")
print(arr_2d)
print("\n")

Print 2D Array
[[  1   2 100]
 [  4   5   6]
 [  7   8   9]]


Print Index [[0,1] , [1,2]] of 2D Array
[2 6]


Print arr_2d[arr_1d>1] of 2D Array
[[4 5 6]
 [7 8 9]]


Change Value of Index [arr_2d>2] of 2D Array
[[1 2 1]
 [1 1 1]
 [1 1 1]]




In [230]:
arr_3  = np.array([[10,20,30] , [100,200,300] ] )

# iteration 
print(arr_3)
for i in np.nditer(arr_3):
    print(i)

[[ 10  20  30]
 [100 200 300]]
10
20
30
100
200
300
